# Describes the format for available HomeKit services

serverstop:
  name: Stop dScriptServer 
  description: Stops the local dScriptServer instance

serverstart:
  name: Start dScriptServer 
  description: Starts the local dScriptServer instance

updatebutton:
  name: Update dScriptButton
  dscription: Trigger update of virtual Button entity from dScriptBoard
  fields:
    entity_id:
      name: Entity
      description: Name of entity that will be updated
      example:
        - sensor.ds_hauptbad_button2
        - sensor.ds_speis_button1
      selector:
        entity:
          integration: sensor
          domain: dscriptmodule 

