# Describes the format for available HomeKit services

serverstop:
  name: Stop dScriptServer 
  description: Stops the local dScriptServer instance

serverstart:
  name: Start dScriptServer 
  description: Starts the local dScriptServer instance

